version: 2
jobs:
  test:
    docker:
      - image: node:8.9.4
    working_directory: /home/ubuntu/joi-image-extension
    steps:
      - checkout
      - run: mkdir -p /home/ubuntu/joi-image-extension/artifacts
      - run: npm install
      - run: npm test
      - store_artifacts:
          path: /home/ubuntu/joi-image-extension/artifacts
  publish:
    docker:
      - image: node:8.9.4
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm install
      - run: NODE_ENV=production npm run build
      - run: NODE_ENV=production npm publish
workflows:
  version: 2
  release:
    jobs:
      - test
      - publish:
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
